loadbalancer:
  build: load-balancer/
  links:
  - consul
  ports:
  - "80:80"
  - "1936:1936"

consul:
  command: -server -bootstrap -advertise ROUTABLE_IP
  image: progrium/consul:latest
  ports:
  - "8300:8300"
  - "8400:8400"
  - "8500:8500"
  - "8600:53/udp"
  volumes:
  - "/var/run/docker.sock:/var/run/docker.sock"
  - "consul/config:/etc/consul"
