loadbalancer:
  build: load-balancer/
  links:
  - consul
  ports:
  - "80:80"
  - "1936:1936"

consul:
  command: -server -bootstrap -advertise ROUTABLE_IP
  image: progrium/consul:latest
  ports:
  - "8300:8300"
  - "8400:8400"
  - "8500:8500"
  - "8600:53/udp"
  volumes:
  - "/var/run/docker.sock:/var/run/docker.sock"
  - "consul/config:/etc/consul"

registrator:
  command: consul://consul:8500
  image: progrium/registrator:latest
  links:
  - consul
  volumes:
  - "/var/run/docker.sock:/tmp/docker.sock"

prometheus:
  image: prom/prometheus:latest
  command: -config.file=/config/prometheus.yml
  links:
  - haproxyexporter
  - consulexporter
  ports:
  - "9090:9090"
  volumes:
  - "prometheus/config:/config"

haproxyexporter:
  command: -haproxy.scrape-uri=http://loadbalancer:1936/;csv
  image: prom/haproxy-exporter:latest
  links:
  - loadbalancer

consulexporter:
  command: -consul.server=consul:8500 -web.listen-address=:9101
  image: prom/consul-exporter:latest
  links:
  - consul

promdash:
  build: promdash/ 
  ports:
  - "3000:3000"
  links:
  - prometheus
  environment:
    DATABASE_URL: sqlite3:/tmp/promdash.sqlite3
