loadbalancer:
  build: load-balancer/
  links:
  - consul
  ports:
  - "80:80"
  - "1936:1936"

consul:
  command: -server -bootstrap -advertise ROUTABLE_IP
  image: progrium/consul:latest
  ports:
  - "8300:8300"
  - "8400:8400"
  - "8500:8500"
  - "8600:53/udp"
  volumes:
  - "/var/run/docker.sock:/var/run/docker.sock"
  - "consul/config:/etc/consul"

registrator:
  command: consul://consul:8500
  image: gliderlabs/registrator:v6
  links:
  - consul
  volumes:
  - "/var/run/docker.sock:/tmp/docker.sock"

prometheus:
  image: prom/prometheus:latest
  command: -config.file=/config/prometheus.yml
  links:
  - haproxyexporter
  ports:
  - "9090:9090"
  volumes:
  - "prometheus/config:/config"

haproxyexporter:
  command: -haproxy.scrape-uri=http://loadbalancer:1936/;csv
  image: prom/haproxy-exporter:latest
  links:
  - loadbalancer
